#!/usr/bin/env python3
"""Download AXERA model repositories on an AX board.

The script intentionally uses huggingface_hub instead of git-lfs so boards can
resume downloads and use the hf-mirror endpoint by default.
"""

from __future__ import annotations

import argparse
import os
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable


DEFAULT_ENDPOINT = "https://hf-mirror.com"
DEFAULT_MODEL_ROOT = "/opt/models/her-axera"


@dataclass(frozen=True)
class ModelSpec:
    key: str
    repo_id: str
    local_dir: str
    aliases: tuple[str, ...]
    env: tuple[tuple[str, str], ...] = ()
    note: str = ""


MODEL_SPECS: tuple[ModelSpec, ...] = (
    ModelSpec(
        key="sensevoice",
        repo_id="AXERA-TECH/SenseVoice",
        local_dir="SenseVoice",
        aliases=("sensevoice", "asr-sensevoice"),
        env=(
            ("ENABLE_SENSEVOICE_ASR", "true"),
            ("SENSEVOICE_REPO_PATH", "{path}"),
        ),
    ),
    ModelSpec(
        key="wenet",
        repo_id="AXERA-TECH/WeNet",
        local_dir="WeNet",
        aliases=("wenet", "wenet-onnx"),
        env=(
            ("ENABLE_WENET_ASR", "true"),
            ("WENET_REPO_PATH", "{path}"),
            ("WENET_ONNX_DIR", "{path}/onnx_model"),
            ("WENET_CONFIG_PATH", "{path}/onnx_model/config.yaml"),
            ("WENET_VOCAB_PATH", "{path}/units.txt"),
        ),
        note="wenet_onnx also needs a compatible runner layout; validate paths before enabling it as default.",
    ),
    ModelSpec(
        key="whisper",
        repo_id="AXERA-TECH/Whisper",
        local_dir="Whisper",
        aliases=("whisper", "asr-whisper"),
        note="download only; this backend does not yet expose a dedicated whisper provider.",
    ),
    ModelSpec(
        key="fireredasr",
        repo_id="AXERA-TECH/FireRedASR-AED",
        local_dir="FireRedASR-AED",
        aliases=("fireredasr", "fireredasr-aed", "fire-red-asr"),
        env=(
            ("ENABLE_FIREREDASR_ASR", "true"),
            ("FIREREDASR_REPO_PATH", "{path}"),
            ("FIREREDASR_MODEL_DIR", "{path}/axmodel"),
        ),
    ),
    ModelSpec(
        key="kokoro",
        repo_id="AXERA-TECH/kokoro.axera",
        local_dir="kokoro.axera",
        aliases=("kokoro", "kokoro-tts"),
        env=(
            ("ENABLE_KOKORO_TTS", "true"),
            ("KOKORO_REPO_PATH", "{path}"),
            ("KOKORO_MODEL_DIR", "{path}/axmodel"),
        ),
    ),
    ModelSpec(
        key="zipvoice",
        repo_id="AXERA-TECH/ZipVoice.AXERA",
        local_dir="ZipVoice.AXERA",
        aliases=("zipvoice", "zipvoice-tts"),
        env=(
            ("ENABLE_ZIPVOICE_TTS", "true"),
            ("ZIPVOICE_REPO_PATH", "{path}"),
            ("ZIPVOICE_MODEL_DIR", "{path}/axmodel"),
        ),
    ),
    ModelSpec(
        key="speaker",
        repo_id="AXERA-TECH/3D-Speaker-MT.Axera",
        local_dir="3D-Speaker-MT.Axera",
        aliases=("speaker", "3d-speaker", "3d_speaker", "speaker-recognition"),
        env=(
            ("ENABLE_SPEAKER_RECOGNITION", "true"),
            ("SPEAKER_REPO_PATH", "{path}"),
            ("SPEAKER_MODEL_DIR", "{path}/axmodel"),
        ),
    ),
)


def _spec_by_alias() -> dict[str, ModelSpec]:
    specs: dict[str, ModelSpec] = {}
    for spec in MODEL_SPECS:
        specs[spec.key] = spec
        for alias in spec.aliases:
            specs[alias] = spec
    return specs


def resolve_models(names: Iterable[str]) -> list[ModelSpec]:
    requested = [name.strip().lower() for name in names if name.strip()]
    if not requested or "all" in requested:
        return list(MODEL_SPECS)

    specs_by_alias = _spec_by_alias()
    selected: list[ModelSpec] = []
    seen: set[str] = set()
    for name in requested:
        spec = specs_by_alias.get(name)
        if spec is None:
            valid = ", ".join(["all", *(spec.key for spec in MODEL_SPECS)])
            raise SystemExit(f"Unknown model '{name}'. Valid values: {valid}")
        if spec.key not in seen:
            selected.append(spec)
            seen.add(spec.key)
    return selected


def render_env(specs: Iterable[ModelSpec], root: Path, endpoint: str) -> str:
    lines = [
        "# Generated by backend/tools/download_ax_models.py",
        f"HF_ENDPOINT={endpoint}",
        f"HER_AXERA_MODEL_ROOT={root}",
        "",
    ]
    for spec in specs:
        path = root / spec.local_dir
        lines.append(f"# {spec.key}: {spec.repo_id}")
        if spec.note:
            lines.append(f"# NOTE: {spec.note}")
        if not spec.env:
            lines.append("# No backend env vars are available for this model yet.")
        for key, template in spec.env:
            lines.append(f"{key}={template.format(root=root, path=path)}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def download_models(
    specs: Iterable[ModelSpec],
    *,
    root: Path,
    endpoint: str,
    revision: str | None,
    token: str | None,
    max_workers: int,
    force_download: bool,
    dry_run: bool,
) -> None:
    from huggingface_hub import snapshot_download

    os.environ.setdefault("HF_ENDPOINT", endpoint)
    if not dry_run:
        root.mkdir(parents=True, exist_ok=True)
    for spec in specs:
        target = root / spec.local_dir
        print(f"[download] {spec.repo_id} -> {target}")
        result = snapshot_download(
            repo_id=spec.repo_id,
            repo_type="model",
            revision=revision,
            local_dir=target,
            endpoint=endpoint,
            token=token,
            max_workers=max_workers,
            force_download=force_download,
            dry_run=dry_run,
        )
        if dry_run:
            print(f"[dry-run] {spec.repo_id}: {len(result)} files")
        else:
            print(f"[done] {spec.key}: {result}")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Download Her.axera AX model repositories on an AX board.")
    parser.add_argument(
        "models",
        nargs="*",
        help="Models to download: all, sensevoice, wenet, whisper, fireredasr, kokoro, zipvoice, speaker.",
    )
    parser.add_argument(
        "--root",
        type=Path,
        default=Path(os.getenv("HER_AXERA_MODEL_ROOT", DEFAULT_MODEL_ROOT)),
        help=f"Model root directory. Default: {DEFAULT_MODEL_ROOT}",
    )
    parser.add_argument(
        "--endpoint",
        default=os.getenv("HF_ENDPOINT", DEFAULT_ENDPOINT),
        help=f"Hugging Face endpoint. Default: {DEFAULT_ENDPOINT}",
    )
    parser.add_argument("--revision", default=None, help="Optional git revision, branch, or tag.")
    parser.add_argument("--token", default=os.getenv("HF_TOKEN"), help="Optional Hugging Face token.")
    parser.add_argument("--max-workers", type=int, default=4, help="Parallel download workers.")
    parser.add_argument("--force-download", action="store_true", help="Re-download files even when cached.")
    parser.add_argument("--dry-run", action="store_true", help="List files without downloading them.")
    parser.add_argument("--env-file", type=Path, help="Write backend env snippet to this file.")
    parser.add_argument("--print-env", action="store_true", help="Print backend env snippet after downloading.")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    specs = resolve_models(args.models)
    download_models(
        specs,
        root=args.root,
        endpoint=args.endpoint,
        revision=args.revision,
        token=args.token,
        max_workers=args.max_workers,
        force_download=args.force_download,
        dry_run=args.dry_run,
    )
    env_text = render_env(specs, args.root, args.endpoint)
    if args.env_file:
        args.env_file.parent.mkdir(parents=True, exist_ok=True)
        args.env_file.write_text(env_text, encoding="utf-8")
        print(f"[env] wrote {args.env_file}")
    if args.print_env:
        print(env_text, end="")


if __name__ == "__main__":
    main()
